project:
  type: website

website:
  title: "Queerologie"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MaxenceOuafik
        aria-label: Profil GitHub
      - icon: twitter
        href: https://twitter.com/Queerologie
        aria-label: Profil Twitter
      - icon: "{{{< ai google-scholar >}}}" 
        href: google.com
format:
  html:
    theme: cosmo
    css: styles.css



