project:
  type: website
  execute-dir: file

website:
  title: "Queerologie"
  repo-url: https://github.com/MaxenceOuafik/Queerologie
  favicon: /img/logo.svg
  open-graph: true
  twitter-card: 
    creator: "@queerologie"
  site-url: "https://querologie.org"
  search: true
  back-to-top-navigation: true
  navbar:
    logo: /img/logo.svg
    pinned: true
    collapse: true
    left:
      - icon: github
        href: https://github.com/MaxenceOuafik
        aria-label: Profil GitHub
      - icon: twitter
        href: https://twitter.com/Queerologie
        aria-label: Profil Twitter
      - icon: rss
        href: index.xml
    right: 
      - text: A propos de l'auteur
        href: about.qmd
  cookie-consent: false
  page-footer: 
    center:
      - text: Ce site et tout son contenu sont en licence CC-BY-NC
format:
  html:
    lang: fr
    language: 
      fr:
        title-block-author-single: "Auteur"
    theme: 
      light: journal
      dark: darkly


