---
title: Guidelines
subtitle: La Cass des soins 
bibliography: "./cass.bib"
draft: true
---
## Contexte
Dans son [rapport final](https://cass.independent-review.uk/home/publications/final-report/) sur la prise en charge des mineur·e·s trans, le Dr. Hillary Cass s'est appuyé sur une série de revues systématiques de la littérature publiées dans [Archives of Disease in Childhood](https://adc.bmj.com/pages/gender-identity-service-series). Le **Cass Report** se présente comme un rapport indépendant répondant aux plus hauts standards méthodologiques. L'objectif de cet article, ainsi que [des autres papiers de cette série](cass-series.html) est de montrer que les bases scientifiques sur lesquelles il s'appuie pour émettre ses recommendations sont fragiles. Vu l'instrumentalisation de ce rapport pour réduire l'accès au soin des mineur·e·s trans, ces textes visent à constituer un argumentaire accessible et rigoureux à destination de toutes les personnes qui ont réellement à coeur leur bien-être. 

Dans cet article, je me pencherai sur l'une de ces revues de la littérature, qui visait à évaluer les guidelines existantes sur la prise en charge des mineur·e·s trans [@taylor2024clinical1]. La première partie visera à décrire ce qui a été fait tandis que la deuxième détaillera les manquements méthodologiques du rapport. 

## Résumé de l'article {#sec-resum}

L'article représente la première partie d'une revue en deux parties. Il vise à décrire la méthodologie de la revue de littérature ainsi qu'à examiner la qualité et le développement des guidelines. La deuxième partie de cette revue [@taylor2024clinical2] ne sera pas étudiée dans le détail, puisqu'il s'agit d'une simple synthèse des recommendations des différentes guidelines et que tous les éléments méthodologiques discutables sont développés dans ce papier.

Ce papier incluait tout document en anglais ou dans une langue "qui pouvait être traduite de manière fiable" [@taylor2024clinical1, p.2 ; traduction personnelle] contenant au moins une recommendation pour l'évaluation ou le traitement des mineur·e·s trans. Les guidelines étaient ensuite évaluées via l'outil AGREE-II [@brouwers2010agree] par trois reviewers en vue de juger de leur qualité. 

Sur les 23 guidelines identifiées, 19 ont été analysées, 4 ne présentant pas d'information suffisante sur leur conception. 
Si la plupart ont été jugées comme claires et avec un champs et des objectifs convenables, leur applicabilité, leur indépendance éditoriale et leur rigueur méthodologique ont été critiquée. Ainsi, seules 6 guidelines ont obtenu un score > 30% et seules les guidelines suédoises ont dépassé les 70%. Par conséquent, seules les guidelines suédoises et finlandaises ont été recommendées par les auteurs, notamment en raison d'un score > 50% pour leur rigueur méthodologique.

::: {.callout-note collapse="true"}

### Pour aller plus loin

Cette revue de littérature s'appuie sur un protocole prépublié sur PROSPERO [@fraser2021epidemiology]. 

La stratégie de recherche est la même que pour toutes les autres revues de la série et s'appuie sur une équation de recherche solide reprenant tous les termes et synonymes pour "enfants" et "adolescents" ainsi que tous les termes en lien avec la "dysphorie de genre", "l'incongruence de genre" ou le fait d'être transgenre. Les bases de données consultées sont Medline, Embase, PsycINFO et CINAHL. Les bases de données ont été cherchées en mai 2021 avec une mise à jour en avril 2022. Les références bibliographiques des guidelines incluses ainsi que des revues systématiques identifiées ont été passées au crible afin d'identifier d'autres documents. Des experts internationaux et des sites internets d'organisation clé ont également été consultées en décembre 2022. 

Pour être retenus, les documents devaient : 

1. Contenir au moins une recommendation pour l'évaluation ou le traitement des mineur·e·s présentant une dypshorie/incongruence de genre
2. Être développés par ou pour des professionnel·le·s, une organisation gouvernementale ou de santé ou une étude.
3. Être rédigés en anglais ou dans une langue "qui pouvait être traduite de manière fiable" 

La qualité des guidelines a été évaluée par trois reviewers à l'aide de l'outil AGREE-II [@brouwers2010agree], un outil validé composé de 23 critères dans six domaines de qualité (champ et objectifs, participation des groupes concernés, rigueur d'élaboration, clarté et présentation, applicabilité et indépendance éditoriale). 

23 guidelines ont été identifiées. Seulement 19 ont été évaluées parce que 4 d'entre elles ne fournissaient pas d'information sur leur développement. La plupart des guidelines ont reçu une évaluation positive pour le champs et l'objectif ainsi que pour la clarté et la présentation. Dans le même temps, la plupart aint reçu un mauvais score pour l'applicabilité, l'indépendance éditoriale et la rigeur du développement. Seules 6 guidelines ont reçu un score > 30% et seules les guidelines suédoises ont reçu un score > 70%. Les seules guidelines recommendées par les auteurs sont les guidelines Suédoises et Finlandaises, seules à avoir reçu un score > 50% pour leur rigeur méthodologique. 

Les reviewers ont également étudié les influences réciproques entre les différentes guidelines et ont constaté que les guidelines s'appuyaient fortement les unes sur les autres. Notamment, de nombreuses guidelines ont été influencées par la 7ème version des standards de soin de la WPATH tandis que la 8ème version des standards s'appuie à son tour sur ces guidelines influencées par une version antérieure. 

Les auteurs concluent donc que la plupart des guidelines manquent d'une approche basée sur les preuves, notamment celles de la WPATH et de l'Endocrine Society, qui ont pourtant dominé le paysage. Ils recommendent donc aux professionnels de la santé de prendre en compte leur manque de qualité et que de meilleures guidelines soient développées. 
:::

## Les problèmes de cet article

À première vue, l'article semble adéquat, a fortiori lorsque l'on n'est pas habitué aux revues systématiques ou que l'on ne connaît pas bien le sujet de la santé des mineur·e·s trans. Toutefois, en y regardant de plus près, plusieurs éléments viennent remettre sérieusement en doute sa crédibilité. 

### Un protocole inexistant

Les auteurs mentionnent comme force de leur étude le fait qu'elle s'appuie sur un protocole prépublié [@taylor2024clinical1, p. 7]. Toutefois, il s'agit d'une distorsion de la réalité. Si les auteurs s'appuient effectivement sur un protocole [@fraser2021epidemiology], celui-ci n'a jamais mentionné cette étude. En effet, aucun des cinq questions de recherche mentionnées dans le protocole ne faisait référence à une analyse des guidelines. Autrement dit, le protocole ne prévoyait pas de faire cette étude et il est pour le moins curieux de le mentionner comme force. 

::: {.callout-caution}
#### Pourquoi est-ce un problème ?

Lorsque l'on publie une revue systématique de la littérature, il est indispensable de s'appuyer sur un protocole prépublié publiquement. Cela permet de vérifier que les auteurs ont bien fait ce qu'ils avaient prévu de faire. Toute modification par rapport au protocole initial doit être justifiée. Ne pas le faire constitue un manque de transparence qui peut laisser planer le doute sur une volonté de modifier la méthodologie au fur et à mesure de l'étude en vue d'arriver à un résultat prédéterminé.

Dans ce cas de figure, il est impossible de savoir si les auteurs s'en sont tenus au plan initial ou s'ils l'ont modifié en cours de route, puisque cette étude est elle-même une déviation du plan de base. 
:::

### Un curieux changement de langue

Le premier point qui m'a intrigué dans cette étude était le choix de la langue. Alors que le protocole prévoit de se limiter à l'anglais [@fraser2021epidemiology, p. 5] et que toutes les autres revues de littérature conduites par cette équipe pour le **Cass Report** se sont limitées à l'anglais, les auteurs ont ici décidé d'élargir à toute langue "qui pouvait être traduite de manière fiable", résultant ainsi à l'inclusion des guidelines suédoises et finlandaises. 

Se limiter à des études publiées en anglais est une pratique découragée pour les revues systématique, parce que cela accroît le risque de biais [@lefebvre2023chapter, section 4.4.5]. Dans l'absolu, c'est donc une bonne chose que les auteurs aient choisi de ne pas répéter cette erreur ici. Toutefois, on est en droit de se demander pourquoi, sur 7 revues de la littérature conduites simultanément, c'est la seule à procéder de la sorte. 

Par ailleurs le critère de sélection est ambigu. Il est impossible, à la lecture de l'article de savoir quelles sont les langues qui ont finalement été inclues. Quelles sont les langues qui ont été considérées comme pouvant être traduites de manière fiables ? Comment les articles individuels ont-ils été traduits ? Une traduction de ces articles est-elle disponible quelque part ? L'article n'apportera aucune question. 

::: {.callout-caution}
#### Pourquoi est-ce un problème ?

Comme tout article scientifique, une revue systématique de la littérature doit être reproductible. Cela signifie que si une équipe indépendante utilisait les mêmes critères, elle devrait aboutir à la même sélection d'études et aux mêmes résultats. Or, sans savoir quelles langues étaient finalement éligibles, il est impossible de reproduire cet article. 

Par ailleurs, et en lien avec le point précédent, vu qu'il n'y avait pas de protocole spécifique à cette étude et que le protocole général, ainsi que les 6 autres revues, se sont limitées à l'anglais, il est impossible de savoir si les auteurs avaient en tête de ne pas mettre de restriction linguistique stricte depuis le début ou bien s'ils ont finalement fait ça parce qu'ils sont tombées sur des guidelines qui les arrangeaient bien. Ce qui nous amène précisément au point suivant.
:::

### Le double standard de l'évaluation

```{r}
#| include: false
rigor <- c(44, 12, 24, 51, 10, 44, 42, 39, 12, 16, 30, 12, 13, 19, 17, 21, 18, 71, 23, 26, 35)
m_rigor <- round(mean(rigor), digits = 0)
sd_rigor <- round(sd(rigor), digits = 0)
```

Comme expliqué dans le @sec-resum, seules les guidelines suédoises et finlandaises ont été recommendées par les auteurs, notamment en raison de leur rigueur méthodologique > 50%. Un rapide coup d'oeil à leur grille de cotation [@taylor2024clinical, p. 5] montre en effet que ces deux études se démarquent *clairement* du lot. En effet, la rigueur méthodologique moyenne était de  `{r} m_rigor`% avec un écart-type de `{r} sd_rigor`%. Or, les guidelines suédoises ont obtenu un score 51% et les guidelines finlandaises, un score de 71% ! Cela correspond à une différence de plus de deux écarts-types pour les suédoises et de plus de 3 écarts-types pour les finlandaises ! En des termes plus concrets, il s'agit de valeurs aberrantes (ou **outliers**, en anglais), soit des valeurs qui s'écartent nettement de la tendance générale. 

On est donc en droit de s'attendre à des guidelines particulièrement extraordinaires. Or, les références de l'article pour les guidelines suédoises pointent vers un [document PDF non traduit](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/kunskapsstod/2022-12-8302.pdf). En passant ce document dans DeepL Pro, ce que les auteurs avaient évoqué comme manière potentielle de traduire certains articles, une surprise de taille nous attend : il n'y a aucune information sur la méthodologie ! Juste la mention d'un fichier annexe reprenant la méthodologie. En cherchant sur le site de la sécurité sociale suédoise, et après quelques erreurs 404, il est possible de retrouver [l'annexe en question](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/kunskapsstod/2022-12-8302-kunskapsunderlag-med-metodbeskrivning.pdf) qui donne davantage d'informations. Toutefois, il est curieux que ces guidelines, qui ont pourtant eu un score aussi élevé, ne donnaient aucune information sur leur méthodologie dans le texte principal, ce qui a été suffisant pour exclure 4 guidelines sur les 23 identifiées. 
L'étude de cette annexe permet aussi de voir, page 64 de la version traduite par DeepL Pro, que les guidelines suédoises ont été envoyées à des associations trans pour avoir leur feedback. Sans surprise, les associations se sont inquiétées du caractère restrictif de ces guidelines. Ces inquiétudes n'ont évidemment pas été prises en compte, mais cela n'a pas empêché les auteurs de cette revue de leur accorder un score de 87% pour la participation des personnes concernées !

La référence pour les guidelines finlandaises renvoient sur une [page internet](https://palveluvalikoima.fi/en/recommendations#genderidentity) où il est possible de les télécharger. On tombe cette fois-ci sur un document de 10 pages (!) ne contenant, une fois de plus, aucune mention de la méthodologie. En enquêtant un peu, il est possible de retrouver [une annexe](https://palveluvalikoima.fi/documents/1237350/22895008/Valmistelumuistio_sukupuoli-identiteetin+variaatiot.pdf/991c7413-3bd5-3e9d-52c4-24c4e2a7a9e5/Valmistelumuistio_sukupuoli-identiteetin+variaatiot.pdf?t=1592317702000) contenant davantage d'informations. Notamment le fait qu'une revue de la littérature a été conduite pour réaliser ces recommendations, laquelle...figure dans une autre annexe ! De la même manière que pour les guidelines sudéoises, les voix des personnes concernées ont été sollicitées et ignorées, malgré un score de 69% pour cet item.

Arrêtons la blague et résumons un peu : les deux guidelines les plus rigoureuses méthodologiquement sont donc celles qui ne contiennent pas de méthodologie et pour lesquelles il faut faire un jeu de piste à travers des sites institutionnels finlandais et suédois pour découvrir, annexe après annexe, comment le projet a été mené ! La vraie raison pour laquelle ces guidelines sont considérées comme rigoureuses est donnée en pages 6-7 de l'article [@taylor2024clinical1] : "En raison de cela, l'équipe de revue n'a recommandé que deux guidelines pour la pratique clinique : les guidelines  finlandaises publiées en 2020 et les guidelines suédoises publiées en 2022 [...]. Ce sont les seules guidelines à publier des détails sur la manière dont ses concepteurs ont analysé et utilisé la base de connaissances ainsi sur leur raisonnement derrière leurs recommendations. Par exemple, ils lient explicitement le manque de preuves solides sur les traitements médicaux pour les adolescents, tel qu'établi à partir de leurs propres revues systématiques, à la recommandation d'une approche plus prudente du traitement et à la nécessité que les services de genre fournissant ces traitements collectent des données sur les résultats, la Suède recommandant que les traitements médicaux ne devraient avoir lieu que dans le cadre de la recherche."

Autrement dit, ce sont les guidelines les plus rigoureuses parce que ce sont les seules qui pensent qu'on devrait restreindre les traitements d'affirmation de genre des mineurs. 

::: {.callout-caution}
#### Pourquoi est-ce un problème ?

Bien que les auteurs aient utilisé un bon outil d'évaluation des guidelines, leur manière de les côter soulève des questions. En effet, les guidelines suédoises et finlandaises sont côtées tellement au-dessus des autres qu'elles représentent des valeurs aberrantes par rapport à la moyenne. Or, aucune des deux ne comporte de méthodologie dans le texte principal, ce qui aurait dû les disqualifier, et les guidelines finlandaises font à peine 10 pages ! L'évaluation de la qualité des guidelines semble donc avoir plus à faire avec ce qu'elles recommendent plutôt qu'à la manière dont elles ont été élaborées. 

Avec ce raisonnement, aucune guideline qui aurait proposé une vision trans-affirmative n'aurait pu être considérée comme rigoureuse. Or, l'évaluation d'une guideline doit se baser sur comment elle a été élaborée. "Je trouve qu'ils n'ont pas été rigoureux parce qu'avec les mêmes données, j'aurais donné une autre recommendation" n'équivaut pas à évaluer la rigueur. C'est un détournenement de ce processus d'évaluation qui pénalise les études avec lesquelles on est en désaccord ; de la malhonnêteté intellectuelle. 
::: 

## Un bel exemple de cherry picking

Résumons : 

1. Cet article n'avait pas été prévu par le protocole initial alors que les auteurs valorisent ledit protocole comme force de l'étude. Il est donc impossible d'évaluer s'ils ont fait le travail honnêtement ou s'ils ont modifié leurs critères en cours de route pour aboutir à un résultat prédéterminé 
2. A la différence des 6 autres études publiées pour le **Cass Report** celle-ci inclut d'autres langues que l'anglais, sans qu'il soit possible de déterminer quelles langues exactement ont été jugées comme éligibles. Cela a permis d'inclure les guidelines suédoises et finlandaises, les deux seules à proposer une approche restrictive, telle que finalement préconisée par le **Cass Report**. 
3. Ces guidelines ont été évaluées largement au-dessus de la moyenne et sont les deux seules à être recommandées, alors qu'elles ne contiennent aucune méthodologie dans leur texte principal, et que les guidelines finlandaises pourraient tenir sur un postit. En outre, malgré d'excellents scores pour la participation des personnes concernées, leurs valeurs n'ont pas été entendues ni retenues pour l'élaboration de ces guidelines. 

Au vu de tout cela, un tableau se dégage clairement, celui d'une étude qui a été mise au point pour montrer ce qu'elle voulait montrer, et non parce qu'il s'agissait de la conclusion la plus probante à la lecture des données. Cela n'est sans doute pas étonnant quand on se rappelle que Riittakerttu Kaltiala, médecin militant contre les traitements d'affirmation de genre avant 18 ans, faisait partie du comité consultatif du **Cass Report**... ainsi que de celui des fameuses guidelines finlandaises.

Cette étude représente, à mon sens,  un exemple frappant de **cherry picking**, c'est-à-dire la sélection trompeuse de données qui appuient une opinion et la mise sous silence de tout ce qui pourrait la contredire.

Soit l'exact contraire de ce que devrait être une revue systématique de la littérature.
