---
title: Guidelines
subtitle: La Cass des soins 
bibliography: "./cass.bib"
draft: true
---
## Contexte
Dans son [rapport final](https://cass.independent-review.uk/home/publications/final-report/) sur la prise en charge des mineur·e·s trans, le Dr. Hillary Cass s'est appuyé sur une série de revues systématiques de la littérature publiées dans [Archives of Disease in Childhood](https://adc.bmj.com/pages/gender-identity-service-series). Le **Cass Report** se présente comme un rapport indépendant répondant aux plus hauts standards méthodologiques. L'objectif de cet article, ainsi que [des autres papiers de cette série](cass-series.html) est de montrer que les bases scientifiques sur lesquelles il s'appuie pour émettre ses recommendations sont fragiles. Vu l'instrumentalisation de ce rapport pour réduire l'accès au soin des mineur·e·s trans, ces textes visent à constituer un argumentaire accessible et rigoureux à destination de toutes les personnes qui ont réellement à coeur leur bien-être. 

Dans cet article, je me pencherai sur l'une de ces revues de la littérature, qui visait à évaluer les guidelines existantes sur la prise en charge des mineur·e·s trans [@taylor2024clinical1]. La première partie visera à décrire ce qui a été fait tandis que la deuxième détaillera les manquements méthodologiques du rapport. 

## Résumé de l'article

L'article représente la première partie d'une revue en deux parties. Il vise à décrire la méthodologie de la revue de littérature ainsi qu'à examiner la qualité et le développement des guidelines. La deuxième partie de cette revue [@taylor2024clinical2] ne sera pas étudiée dans le détail, puisqu'il s'agit d'une simple synthèse des recommendations des différentes guidelines et que tous les éléments méthodologiques discutables sont développés dans ce papier. 

### Méthodologie

Cette revue de littérature s'appuie sur un protocole prépublié sur PROSPERO [@fraser2021epidemiology]. 

La stratégie de recherche est la même que pour toutes les autres revues de la série et s'appuie sur une équation de recherche solide reprenant tous les termes et synonymes pour "enfants" et "adolescents" ainsi que tous les termes en lien avec la "dysphorie de genre", "l'incongruence de genre" ou le fait d'être transgenre. Les bases de données consultées sont Medline, Embase, PsycINFO et CINAHL. Les bases de données ont été cherchées en mai 2021 avec une mise à jour en avril 2022. Les références bibliographiques des guidelines incluses ainsi que des revues systématiques identifiées ont été passées au crible afin d'identifier d'autres documents. Des experts internationaux et des sites internets d'organisation clé ont également été consultées en décembre 2022. 

Pour être retenus, les documents devaient : 

1. Contenir au moins une recommendation pour l'évaluation ou le traitement des mineur·e·s présentant une dypshorie/incongruence de genre
2. Être développés par ou pour des professionnel·le·s, une organisation gouvernementale ou de santé ou une étude.
3. Être rédigés en anglais ou dans une langue "qui pouvait être traduite de manière fiable" [@taylor2024clinical1, p.2 ; traduction personnelle]. 

La qualité des guidelines a été évaluée par trois reviewers à l'aide de l'outil AGREE-II [@brouwers2010agree], un outil validé composé de 23 critères dans six domaines de qualité (champ et objectifs, participation des groupes concernés, rigueur d'élaboration, clarté et présentation, applicabilité et indépendance éditoriale). 

### Résultats et discussion

23 guidelines ont été identifiées. Seulement 19 ont été évaluées parce que 4 d'entre elles ne fournissaient pas d'information sur leur développement. La plupart des guidelines ont reçu une évaluation positive pour le champs et l'objectif ainsi que pour la clarté et la présentation. Dans le même temps, la plupart aint reçu un mauvais score pour l'applicabilité, l'indépendance éditoriale et la rigeur du développement. Seules 6 guidelines ont reçu un score > 30% et seules les guidelines suédoises ont reçu un score > 70%. Les seules guidelines recommendées par les auteurs sont les guidelines Suédoises et Finlandaises, seules à avoir reçu un score > 50% pour leur rigeur méthodologique. 

Les reviewers ont également étudié les influences réciproques entre les différentes guidelines et ont constaté que les guidelines s'appuyaient fortement les unes sur les autres. Notamment, de nombreuses guidelines ont été influencées par la 7ème version des standards de soin de la WPATH tandis que la 8ème version des standards s'appuie à son tour sur ces guidelines influencées par une version antérieure. 

Les auteurs concluent donc que la plupart des guidelines manquent d'une approche basée sur les preuves, notamment celles de la WPATH et de l'Endocrine Society, qui ont pourtant dominé le paysage. Ils recommendent donc aux professionnels de la santé de prendre en compte leur manque de qualité et que de meilleures guidelines soient développées. 

## Les problèmes de cet article

À première vue, l'article semble adéquat, a fortiori lorsque l'on n'est pas habitué aux revues systématiques ou que l'on ne connaît pas bien le sujet de la santé des mineur·e·s trans. Toutefois, en y regardant de plus près, plusieurs éléments viennent remettre sérieusement en doute sa crédibilité. 

### Un protocole inexistant

Les auteurs mentionnent comme force de leur étude le fait qu'elle s'appuie sur un protocole prépublié [@taylor2024clinical1, p. 7]. Toutefois, il s'agit d'une distorsion de la réalité. Si les auteurs s'appuient effectivement sur un protocole [@fraser2021epidemiology], celui-ci n'a jamais mentionné cette étude. En effet, aucun des cinq questions de recherche mentionnées dans le protocole ne faisait référence à une analyse des guidelines. Autrement dit, le protocole ne prévoyait pas de faire cette étude et il est pour le moins curieux de le mentionner comme force. 

::: {.callout-tip}
#### Pourquoi est-ce important ?

Lorsque l'on publie une revue systématique de la littérature, il est indispensable de s'appuyer sur un protocole prépublié publiquement. Cela permet de vérifier que les auteurs ont bien fait ce qu'ils avaient prévu de faire. Toute modification par rapport au protocole initial doit être justifiée. Ne pas le faire constitue un manque de transparence qui peut laisser planer le doute sur une volonté de modifier la méthodologie au fur et à mesure de l'étude en vue d'arriver à un résultat prédéterminé.

Dans ce cas de figure, il est impossible de savoir si les auteurs s'en sont tenus au plan initial ou s'ils l'ont modifié en cours de route, puisque cette étude est elle-même une déviation du plan de base. 
:::

### Un curieux changement de langue

### Le double standard de l'évaluation



Guidelines suédoises : pas de méthodo ! plusieurs papiers ! quid de la trad ? Réelle participation des enfants/parents ???

## Un bel exemple de cherry picking
